framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
<<<<<<< HEAD
=======
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
>>>>>>> d135cf0c5d236029e00195fec28f03b4ec4c6ca5
